branch-defaults:
  development:
    environment: app-development-73
  master:
    environment: app-production-73
environment-defaults:
  app-development-73:
    branch: null
    repository: null
  app-production-73:
    branch: null
    repository: null
global:
  application_name: app
  default_ec2_keyname: null
  default_platform: PHP 7.3 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
